# Generated by Django 4.2.30 on 2026-04-12 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
