# Generated by Django 4.2.30 on 2026-04-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otprecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Main Admin'), ('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient', max_length=10),
        ),
    ]
