# Generated by Django 4.2.30 on 2026-04-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRecord',
        ),
    ]
