# Generated by Django 4.2.30 on 2026-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_otprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
