# Generated by Django 5.0.1 on 2026-03-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctor_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
