# Generated by Django 5.0.1 on 2026-03-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hospital_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash on hand', 'Cash on hand'), ('Razorpay', 'Razorpay')], default='Cash on hand', max_length=50),
        ),
    ]
