# Generated by Django 5.0.1 on 2026-03-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_callbackrequest_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Mon, Wed, Fri', help_text='Comma-separated days e.g. Mon, Tue, Wed', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
