# Generated by Django 4.2.30 on 2026-04-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_doctor_doctor_id_doctor_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(help_text='Enter a unique Doctor ID manually (e.g. DOC-1001)', max_length=20, null=True, unique=True),
        ),
    ]
