# Generated by Django 4.2.30 on 2026-04-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_doctor_user_alter_doctor_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='generate_method',
            field=models.CharField(choices=[('template', 'Custom Template'), ('upload', 'Uploaded File')], default='template', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/uploads/'),
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name, e.g. 'Viral Fever Protocol'", max_length=255)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('medicines', models.JSONField(default=list)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_templates', to='core.doctor')),
            ],
        ),
    ]
