# Generated by Django 4.2.30 on 2026-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_medicalrecord_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='lab_tests',
            field=models.TextField(blank=True, help_text='Recommended lab tests / investigations', null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='lab_tests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
