# Generated by Django 4.2.30 on 2026-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_prescription_follow_up_date_prescription_lab_tests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='specialties',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(default='Cash on hand', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CallbackRequest',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
