# Generated by Django 4.2.30 on 2026-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_hospital_specialties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients_per_slot',
            field=models.PositiveIntegerField(default=3, help_text='Max patients allowed per time slot'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='shift_end_time',
            field=models.TimeField(default='12:00:00', help_text='End time of shift'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Duration of each slot in minutes'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='shift_start_time',
            field=models.TimeField(default='09:00:00', help_text='Start time of shift'),
        ),
    ]
