# Generated by Django 4.2.30 on 2026-04-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_appointment_last_updated_by_appointment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
    ]
