# Generated by Django 4.2.30 on 2026-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_appointment_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
