# Generated by Django 4.2.30 on 2026-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='weekly_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Day-wise schedule configurations'),
        ),
    ]
