# Generated by Django 4.2.30 on 2026-04-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_doctor_weekly_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescriptiontemplate',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='PrescriptionTemplate',
        ),
    ]
