# Generated by Django 4.2.27 on 2026-01-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_labcategory_alter_labtest_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='category',
        ),
    ]
