# Generated by Django 4.2.27 on 2026-01-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_remove_labtest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='commerce.labcategory'),
        ),
    ]
