# Generated by Django 4.2.27 on 2026-01-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_labtest_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='category',
        ),
    ]
