# Generated by Django 4.2.27 on 2026-01-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0010_remove_labtest_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_tests",
                to="commerce.labcategory",
            ),
        ),
    ]
