# Generated by Django 4.2.30 on 2026-04-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_order_is_paid_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prescription',
        ),
    ]
