# Generated by Django 4.2.30 on 2026-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_remove_order_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='strip_count',
            field=models.PositiveIntegerField(default=10, help_text='Number of tablets/units per strip'),
        ),
    ]
