# Generated by Django 4.2.30 on 2026-04-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_medicine_strip_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='category',
        ),
        migrations.DeleteModel(
            name='LabCategory',
        ),
    ]
