# Generated by Django 4.2.30 on 2026-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_remove_labtest_category_delete_labcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
