# Generated by Django 4.2.30 on 2026-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_labtest_latitude_labtest_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='features',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='price',
        ),
        migrations.AddField(
            model_name='labtest',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
