# Generated by Django 4.2.30 on 2026-04-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_labreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='available_days',
            field=models.CharField(default='Mon, Tue, Wed, Thu, Fri, Sat', help_text='Comma-separated days e.g. Mon, Tue, Wed', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='patients_per_slot',
            field=models.PositiveIntegerField(default=5, help_text='Max patients allowed per time slot'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='shift_end_time',
            field=models.TimeField(default='18:00:00', help_text='End time of shift'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='shift_start_time',
            field=models.TimeField(default='09:00:00', help_text='Start time of shift'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of each slot in minutes'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='unavailable_dates',
            field=models.TextField(blank=True, help_text='Comma-separated dates lab is closed (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='weekly_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Day-wise schedule configurations'),
        ),
    ]
