# Generated by Django 4.2.30 on 2026-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_labtest_available_days_labtest_patients_per_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lab_id',
            field=models.CharField(blank=True, help_text='Unique Lab Portal ID (e.g. LAB-1001)', max_length=20, null=True, unique=True),
        ),
    ]
