# Generated by Django 4.2.30 on 2026-04-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_labtest_lab_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'verbose_name': 'Lab', 'verbose_name_plural': 'Labs'},
        ),
    ]
